import banner1 from "./banner 1.jpg"
import banner2 from "./banner 2.jpg";
import banner3 from "./banner 3.jpg";
import banner4 from "./banner 4.jpg";
import banner5 from "./banner 5.jpg";
import banner6 from "./banner 6.jpg";
import banner7 from "./banner 7.jpg";
import banner8 from "./image 1.jpg";
 export const img = [banner1,banner2,banner3,banner4,banner5,banner6,banner7,banner8]